name: Core Platform CI/CD
on: [push, pull_request]

jobs:
  rust-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build WASM
        run: wasm-pack build packages/wasm --target web
      - name: Run Rust tests
        run: cargo test
      - name: Lint Rust code
        run: cargo clippy -- -D warnings
      - name: Format check
        run: cargo fmt -- --check
  
  typescript-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build orchestration
        run: npm run build:orchestration
      - name: Run TypeScript tests
        run: npm run test:orchestration
      - name: Type check
        run: npm run type-check
      - name: Lint TypeScript
        run: npm run lint:ts
  
  integration-tests:
    needs: [rust-build, typescript-build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install dependencies
        run: npm ci
      - name: Build all
        run: npm run build:all
      - name: Run integration tests
        run: npm run test:integration
      - name: Performance benchmarks
        run: npm run test:performance
