name: Deploy WASM Bundles to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        
      - name: Install dependencies
        run: npm ci
        
      - name: Install orchestration dependencies
        run: cd packages/orchestration && npm ci
        
      - name: Build WASM
        run: npm run build:wasm
        
      - name: Build orchestration
        run: npm run build:orchestration
        
      - name: Create GitHub Pages deployment
        run: |
          mkdir -p dist
          
          # Copy WASM artifacts
          cp -r packages/pkg dist/wasm
          
          # Copy orchestration build
          cp -r packages/orchestration/dist dist/orchestration
          
          # Create index.html for the bundles
          cat > dist/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <title>DataPrism Core - WASM Bundles</title>
              <style>
                  body { font-family: Arial, sans-serif; margin: 40px; }
                  .container { max-width: 800px; margin: 0 auto; }
                  .bundle { background: #f5f5f5; padding: 20px; margin: 20px 0; border-radius: 8px; }
                  .file-list { background: white; padding: 15px; border-radius: 4px; margin: 10px 0; }
                  .file-list a { display: block; margin: 5px 0; color: #0066cc; text-decoration: none; }
                  .file-list a:hover { text-decoration: underline; }
                  .version { color: #666; font-size: 0.9em; }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>DataPrism Core - WASM Bundles</h1>
                  <p class="version">Built from commit: <code>${{ github.sha }}</code></p>
                  
                  <div class="bundle">
                      <h2>WebAssembly Core Engine</h2>
                      <p>High-performance WebAssembly engine with DuckDB integration</p>
                      <div class="file-list">
                          <a href="wasm/dataprism_core.js">dataprism_core.js</a>
                          <a href="wasm/dataprism_core_bg.wasm">dataprism_core_bg.wasm</a>
                          <a href="wasm/dataprism_core.d.ts">dataprism_core.d.ts</a>
                          <a href="wasm/package.json">package.json</a>
                      </div>
                  </div>
                  
                  <div class="bundle">
                      <h2>TypeScript Orchestration</h2>
                      <p>JavaScript orchestration layer for DataPrism Core</p>
                      <div class="file-list">
                          <a href="orchestration/index.js">index.js</a>
                          <a href="orchestration/index.cjs">index.cjs</a>
                      </div>
                  </div>
                  
                  <div class="bundle">
                      <h2>Usage</h2>
                      <p>Include in your project:</p>
                      <pre style="background: #f0f0f0; padding: 15px; border-radius: 4px; overflow-x: auto;">
          // ES Modules
          import init, { DataPrismCore } from 'https://srnarasim.github.io/dataprism-core/wasm/dataprism_core.js';
          
          // Initialize WASM
          await init();
          
          // Use the core engine
          const core = new DataPrismCore();
                      </pre>
                  </div>
                  
                  <div class="bundle">
                      <h2>Documentation</h2>
                      <p>
                          <a href="https://github.com/srnarasim/dataprism-core">GitHub Repository</a> |
                          <a href="https://srnarasim.github.io/dataprism-apps">Full Documentation</a>
                      </p>
                  </div>
              </div>
          </body>
          </html>
          EOF
          
          # Create .nojekyll to ensure GitHub Pages serves all files
          touch dist/.nojekyll
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4